### ISSUE TITLE
issues on a first test run

### ISSUE THREAD

**Issue by tcurdt** [usrz/minimal-ubuntu#1]
I went with the minimal server image as base for the builder OS.

It seems like `dosfstools` should be added to the list of packages required.
Depending on host adding `curl` might also be a good idea.

One strange thing happened: The `postinst` script did not create a user. It did disable the bracketed paste

https://github.com/usrz/minimal-ubuntu/blob/44e24f92bd0d8762671a25e89a8e3e0caf0055c8/minimal-os/DEBIAN/postinst#L13

But the user creation did not run

https://github.com/usrz/minimal-ubuntu/blob/44e24f92bd0d8762671a25e89a8e3e0caf0055c8/minimal-os/DEBIAN/postinst#L41

Did it end prematurely?
I must have missed if there was an error.
But the package seems to be install just fine.

One thing I was wondering:
What's the update cycle of `debootstrap`?

Will the package get updates for the forward releases on Ubuntu?

**Comment by tcurdt** [comment]
The aborting of the `postinst` seems to be repeatable.
Now I need to figure out how to debug it.

**Comment by tcurdt** [comment]
Well, oh, well... it is just 

```
#!/bin/bash

# Update locale if unset in /etc/default/locale
grep -q '^LANGUAGE' '/etc/default/locale' || {
	/usr/sbin/locale-gen en_US.UTF-8
	echo 'Setting default locale to en_US.UTF-8'
	/usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LANGUAGE=en_US
}

# Disable "bracketed paste"
grep -q 'enable-bracketed-paste' '/etc/inputrc' || {
	echo '' >> '/etc/inputrc'
	echo '# Disable "bracketed paste"' >> '/etc/inputrc'
	echo 'set enable-bracketed-paste off' >> '/etc/inputrc'
}
```
:-D

**Comment by pfumagalli** [comment]
Fixed all and updated to Noble.
